"""add driving_distance_mi to trails

Revision ID: 020c14b054b6
Revises: f203d5b4919d
Create Date: 2026-03-21 21:02:58.492124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020c14b054b6'
down_revision = 'f203d5b4919d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driving_distance_mi', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.drop_column('driving_distance_mi')

    # ### end Alembic commands ###
