"""empty message

Revision ID: aa300e33a588
Revises: 
Create Date: 2025-09-16 06:52:19.343953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa300e33a588'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('provider_user_id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tel', sa.String(length=15), nullable=True),
    sa.Column('joined_on', sa.DateTime(), nullable=False),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active_vote_candidate', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('length_mi', sa.Float(), nullable=False),
    sa.Column('estimated_time_hr', sa.Float(), nullable=False),
    sa.Column('required_water_liters', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.Column('alltrails_url', sa.String(length=300), nullable=True),
    sa.Column('trailhead_gmaps_url', sa.String(length=300), nullable=True),
    sa.Column('trailhead_amaps_url', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trail_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('email_campaign_completed', sa.Boolean(), nullable=False),
    sa.Column('has_vote', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('signup_date', sa.DateTime(), nullable=False),
    sa.Column('waiver_date', sa.DateTime(), nullable=False),
    sa.Column('hike_date', sa.DateTime(), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hikes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hikes_hike_date'), ['hike_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hikes_status'), ['status'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('passenger_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hike_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hike_id'], ['hikes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('hike_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_used', sa.DateTime(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hike_id'], ['hikes.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('hike_id', sa.Integer(), nullable=False),
    sa.Column('signup_date', sa.DateTime(), nullable=False),
    sa.Column('transport_type', sa.String(length=20), nullable=False),
    sa.Column('food_interest', sa.Boolean(), nullable=False),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('waitlist_pos', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hike_id'], ['hikes.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('hike_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hike_id'], ['hikes.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('hike_id', sa.Integer(), nullable=False),
    sa.Column('print_name', sa.String(length=50), nullable=False),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('signature_1_b64', sa.Text(), nullable=False),
    sa.Column('signature_2_b64', sa.Text(), nullable=False),
    sa.Column('signed_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hike_id'], ['hikes.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_tasks')
    op.drop_table('waivers')
    op.drop_table('votes')
    op.drop_table('signups')
    op.drop_table('magic_links')
    op.drop_table('email_campaigns')
    op.drop_table('vehicles')
    with op.batch_alter_table('hikes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hikes_status'))
        batch_op.drop_index(batch_op.f('ix_hikes_hike_date'))

    op.drop_table('hikes')
    op.drop_table('trails')
    op.drop_table('members')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
