"""empty message

Revision ID: c26c902ca1a6
Revises: 4bab92dd4c4d
Create Date: 2025-09-14 21:25:43.383410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26c902ca1a6'
down_revision = '4bab92dd4c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hikes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tz', sa.String(length=64), nullable=False))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('tel',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=15),
               existing_nullable=True)

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_interest', sa.Boolean(), nullable=False))

    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_minor', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signature_1_b64', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('signature_2_b64', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.drop_column('signature_2_b64')
        batch_op.drop_column('signature_1_b64')
        batch_op.drop_column('age')
        batch_op.drop_column('is_minor')
        batch_op.drop_column('print_name')

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_column('food_interest')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('tel',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('hikes', schema=None) as batch_op:
        batch_op.drop_column('tz')

    # ### end Alembic commands ###
