"""add elevation_data to trails

Revision ID: d381a197c8f9
Revises: ad5a3ecf1d41
Create Date: 2026-02-16 08:44:32.323157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd381a197c8f9'
down_revision = 'ad5a3ecf1d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elevation_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.drop_column('elevation_data')

    # ### end Alembic commands ###
