"""remove unique constraint on members email

Revision ID: f203d5b4919d
Revises: d381a197c8f9
Create Date: 2026-03-21 20:12:06.480033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f203d5b4919d'
down_revision = 'd381a197c8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('members_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('members_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
