name: PR Auto Describe
on:
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened, labeled]
jobs:
  describe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: PR Auto Describe
        uses: salehhashemi1992/pr-auto-describe@v0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-model: 'gpt-4'
